name: Build and Release Electron App

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Web Assets
        run: pnpm web:build

      - name: Build Electron App
        run: pnpm electron:build

      - name: Build Executable with Electron-Builder
        run: pnpm electron-builder

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          path: dist/**

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/**
          asset_name: app-build.zip
          asset_content_type: application/zip
