name: Build and Release Electron App

on:
  push:

jobs:
  build-and-release:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Web Assets
        run: pnpm web:build

      - name: Build Electron App
        run: pnpm electron:build

      - name: Build Executable with Electron-Builder
        run: pnpm release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
